alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -alhF --color --group-directories-first'
alias tfapply='source /tfcli/apply.sh'
alias tfauth='source  /tfcli/auth.sh'
alias tfdestroy='source /tfcli/destroy.sh'
alias tfimport='source /tfcli/import.sh'
alias tfinit='source /tfcli/init.sh'
alias tfoutput='source /tfcli/output.sh'
alias tfplan='source /tfcli/plan.sh'
alias tfset='source /tfcli/setup.sh'