services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.dev.local
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev.local
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]