FROM node:lts-alpine as base
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY ./nginx/production/default.conf /etc/nginx/conf.d/default.conf
COPY --from=base /app/build /usr/share/nginx/html