FROM ubuntu:22.04

ARG TERRAFORM_VERSION=1.9.0

WORKDIR /root/tfcli

COPY ./functions ./functions
COPY ./scripts .
COPY ./starship/starship.toml .config/starship.toml
COPY load_functions.sh .

# Update and upgrade apt
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential curl file git jq zip unzip shellcheck gnupg software-properties-common

# Install Azure Cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install JetBrains fonts
RUN curl -fsSL https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip --output JetBrainsMono.zip
RUN unzip JetBrainsMono.zip -d /usr/share/fonts

#Install Starship command prompt
RUN curl -fsSL https://starship.rs/install.sh --yes | sh

# Install Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
RUN apt-get update
RUN apt-get install terraform
RUN terraform -install-autocomplete

# Install Keychain
RUN apt-get install -y keychain

ENTRYPOINT [ "bash", "-c", "/root/tfcli/load_functions.sh" ]












