FROM ubuntu:24.04

ENV TARGETARCH="linux-x64"

ARG TERRAFORM_VERSION="1.0.0"

# To make it easier for build and release pipelines to run apt,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN echo 'Updating the list of available packages and versions, upgrading installed packages, and installing essential packages'
RUN apt update && apt upgrade -y -qq && apt install -y --no-install-recommends \
    apt-transport-https \
    build-essential \
    ca-certificates \
    curl \
    figlet \
    jq \
    software-properties-common \
    wget \
    gpg \
    gnupg \
    unzip

RUN echo 'Setting environment variables'
RUN echo 'export PATH="$PATH:/home/$(whoami)/.local/bin"' >> ~/.bashrc

RUN echo 'Installing Az Cli'
# Install Azure Cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN echo 'Installing Terraform'
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
RUN rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
# Verify installation
RUN terraform --version

# Remove cache files
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /azp/

COPY artifacts/start.sh .
RUN chmod +x start.sh

# Create agent user and set up home directory
RUN useradd -m -d /home/agent agent
RUN chown -R agent:agent /azp /home/agent

USER agent

ENTRYPOINT ["./start.sh"]