resources:
  repositories:
  - repository: azdo_pipelines
    name: {project_name}/azdo_pipelines
    type: git
    ref: main

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - base_linux_image/Dockerfile

variables:
  - template: variables.yml

jobs:
  - job: docker_build
    displayName: 'Docker build'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - template: Docker/docker_build.yml@azdo_pipelines
      parameters:
        acr: $(container_registry)
        dockerfile_path: $(dockerfile_path)
        image_repository: $(image_repository)
        service_connection: $(service_connection)
        tags: $(tags)