name: Test Client Docker Build
on:
  pull_request: 
    branches:
      - '*'
    paths:
      - 'projects/production_grade_flow/client/dockerfile*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests on docker image

    defaults:
      run:
        working-directory: ./projects/production_grade_flow/client

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/client -f dockerfile.dev .

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: docker run with tests
        run: docker run -e CI=true ${{ vars.DOCKER_USERNAME }}/client npm test
