name: Deploy Infra

on:
  push:
    branches: master

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure using Terraform
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: auth
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
        
