name: Deploy Infra

on:
  push:
    branches: master

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure using Terraform
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      # - name: auth
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     enable-AzPSSession: true

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
      
      - name: terraform init and plan
        id: init
        run: |
          cd ./iac/frontend_app_service

          # export variables as environment variables
          export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
          export ARM_SUBSCRIPTION_ID=${{ vars.ARM_SUBSCRIPTION_ID }}

          terraform init -upgrade -input=false
          terraform plan
        
