name: Test Fibonacci Calculator Api
on:
  pull_request: 
    branches:
      - '*'
    paths:
      - 'projects/fibonacci_calculator/api/dockerfile*'

jobs:
  check_for_vulnerabilities:
    runs-on: ubuntu-latest
    name: Check for vulnerabilities

    permissions:
      contents: read
      pull-requests: read
      repository-projects: read

    defaults:
      run:
        working-directory: ./projects/fibonacci_calculator/api

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
    
      - name: Build Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/api:${{ github.run_number }} -f dockerfile .
      
      - name: Check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ vars.DOCKER_USERNAME }}/api:${{ github.run_number }}
          args: --file=./projects/fibonacci_calculator/api/dockerfile
        
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif