name: Deploy Frontend
on:
  pull_request: 
    branches:
      - '*'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ./projects/production_grade_flow/frontend
          docker build -t heathen1878/testme -f dockerfile.dev .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker run -e CI=true heathen1878/testme npm test
