name: Plan Infra
on:
  pull_request: 
    branches:
      - '*'
    paths:
      - '**.tf'


jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    name: Plan Infrastructure using Terraform
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: auth
        uses: azure/login@v2
        with:
          creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}", "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}"}'

      - name: get runner ip
        id: runner_ip
        run: |
          IP_ADDR=$(curl -s https://ifconfig.me/ip)
          echo "IPADDR=$IP_ADDR" >> $GITHUB_ENV

      - name: modify state storage acl
        run: |
          echo $IPADDR
          az storage account network-rule add --account-name ${{ vars.STATE_STORAGE_ACCOUNT }} --ip-address $IPADDR --subscription ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}
      
      - name: terraform init and plan
        id: init
        run: |
          cd ./iac/frontend_app_service

          # export variables as environment variables
          export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
          export ARM_SUBSCRIPTION_ID=${{ vars.ARM_SUBSCRIPTION_ID }}
          export ARM_USE_AZUREAD=true

          terraform init \
          -upgrade \
          -input=false \
          -backend-config="storage_account_name=${{ vars.STATE_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ vars.STATE_STORAGE_CONTAINER }}" \
          -backend-config="key=${{ vars.STATE_FILE_NAME }}"

          terraform plan
      
      - name: modify state storage acl - clean up
        run: |
          echo $IPADDR
          az storage account network-rule remove --account-name ${{ vars.STATE_STORAGE_ACCOUNT }} --ip-address $IPADDR --subscription ${{ vars.ARM_SUBSCRIPTION_ID }}
  
