name: Push Frontend To Docker Hub

on:
  push:
    branches: master

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Frontend to Docker Hub
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: docker build
        run: |
            cd ./projects/production_grade_flow/frontend
            docker build -t heathen1878/demo:latest -f dockerfile .

      - name: docker push
        run: |
          docker image push heathen1878/demo:latest